### ISSUE TITLE
Skidding

### ISSUE THREAD

**Issue by xenitrogen** [Pluto-Client/Pluto-Client-V3#1]
Weren't you the guy who coded the client & skidded it.
![image](https://user-images.githubusercontent.com/69071363/125291731-9f3a0780-e319-11eb-8890-6f24609f72b0.png)

**Comment by PaceSomesh** [comment]
Isaam is literally spreading misinformation about me, I didn't had the client src he gave a previous src made by chron I just implemented the client src and gave to Isaam.

**Comment by YeahOMA** [comment]
Nah Pace is special in the head and doesnt even know shit about programming (When he says he knows multiple programming languages) when I asked him what a Mixin was he folded harder than a north korean child being run over by a truck.

He is so retarded that he leaks client sources (Because he fanboys me) and calls them out for skidding when in reality he has never rewritten a single line of original code in his life.

Fold harder, retard.

**Comment by xxxOMA** [comment]
Lmfaooooooo you deleted my comment cry harder LOL

**Comment by xxxOMA** [comment]
Indian faggot
